import { ref, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import itemRequestService from '@/stores/itemRequestService';
// ================================================================
// STATE
// ================================================================
const router = useRouter();
const route = useRoute();
const loading = ref(true);
const requestData = ref(null);
const stores = ref([]);
const items = ref([]);
// ================================================================
// METHODS
// ================================================================
const loadStores = async () => {
    try {
        const response = await itemRequestService.getActiveStores();
        if (response.success) {
            stores.value = response.data;
        }
    }
    catch (error) {
        console.error('Load stores error:', error);
    }
};
const loadItems = async () => {
    try {
        const response = await itemRequestService.getActiveItems();
        if (response.success) {
            items.value = response.data;
        }
    }
    catch (error) {
        console.error('Load items error:', error);
    }
};
const loadRequest = async (requestId) => {
    try {
        const response = await itemRequestService.getRequestById(Number(requestId));
        if (response.success) {
            requestData.value = response.data;
        }
    }
    catch (error) {
        console.error('Load request error:', error);
    }
    finally {
        loading.value = false;
    }
};
// -- Helper Methods --
const getStoreName = (storeId) => {
    const store = stores.value.find(s => (s.storeId || s.id) === storeId);
    return store ? store.name : 'Unknown Store';
};
const getStoreCode = (storeId) => {
    const store = stores.value.find(s => (s.storeId || s.id) === storeId);
    return store ? store.code : 'N/A';
};
const getItemName = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    return item ? item.name : 'Unknown Item';
};
const getItemCode = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    return item ? item.code : 'N/A';
};
const getItemBrand = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    return item?.brand || '';
};
const getItemModel = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    return item?.model || '';
};
const getItemUOM = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    if (item?.uom) {
        if (typeof item.uom === 'string')
            return item.uom;
        if (typeof item.uom === 'object' && item.uom.code)
            return item.uom.code;
    }
    return '';
};
const getItemSpecification = (itemId) => {
    const item = items.value.find(i => (i.itemId || i.id) === itemId);
    return item?.specText || '';
};
const getRequesterName = () => {
    if (!requestData.value)
        return 'N/A';
    if (requestData.value.requestedByUser) {
        return requestData.value.requestedByUser.fullName ||
            requestData.value.requestedByUser.full_name ||
            requestData.value.requestedByUser.username ||
            'N/A';
    }
    return requestData.value.requestedBy || 'N/A';
};
const formatDate = (dateString) => {
    if (!dateString)
        return 'N/A';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
};
/**
 * Filter and remove all HTML elements/entities generated by rich text editors
 */
const stripHtml = (htmlContent) => {
    if (!htmlContent)
        return '';
    return htmlContent
        .replace(/<[^>]*>/g, '') // Strips out matching HTML tags
        .replace(/&nbsp;/g, ' ') // Replaces rich text space entity breaks
        .replace(/&amp;/g, '&') // Decodes basic text entities
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .trim();
};
// -- Navigation --
const goBack = () => {
    router.push('/item-requests');
};
const printPage = () => { window.print(); };
// ================================================================
// LIFECYCLE
// ================================================================
onMounted(async () => {
    const requestId = route.query.id;
    if (requestId) {
        await Promise.all([
            loadStores(),
            loadItems()
        ]);
        await loadRequest(requestId);
    }
    else {
        loading.value = false;
    }
});
const __VLS_ctx = {
    ...{},
    ...{},
};
let __VLS_components;
let __VLS_intrinsics;
let __VLS_directives;
/** @type {__VLS_StyleScopedClasses['items-table']} */ ;
/** @type {__VLS_StyleScopedClasses['items-table']} */ ;
/** @type {__VLS_StyleScopedClasses['items-table']} */ ;
/** @type {__VLS_StyleScopedClasses['items-table']} */ ;
/** @type {__VLS_StyleScopedClasses['input-row']} */ ;
/** @type {__VLS_StyleScopedClasses['write-line']} */ ;
/** @type {__VLS_StyleScopedClasses['checked-by-body']} */ ;
/** @type {__VLS_StyleScopedClasses['print-page']} */ ;
/** @type {__VLS_StyleScopedClasses['gray-label']} */ ;
/** @type {__VLS_StyleScopedClasses['block-header']} */ ;
/** @type {__VLS_StyleScopedClasses['items-table']} */ ;
if (__VLS_ctx.requestData || !__VLS_ctx.loading) {
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "top-actions no-print" },
    });
    /** @type {__VLS_StyleScopedClasses['top-actions']} */ ;
    /** @type {__VLS_StyleScopedClasses['no-print']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.button, __VLS_intrinsics.button)({
        ...{ onClick: (__VLS_ctx.goBack) },
        ...{ class: "btn-back-top" },
    });
    /** @type {__VLS_StyleScopedClasses['btn-back-top']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.button, __VLS_intrinsics.button)({
        ...{ onClick: (__VLS_ctx.printPage) },
        ...{ class: "btn-print-top" },
    });
    /** @type {__VLS_StyleScopedClasses['btn-print-top']} */ ;
}
if (__VLS_ctx.requestData) {
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "print-page" },
    });
    /** @type {__VLS_StyleScopedClasses['print-page']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.header, __VLS_intrinsics.header)({
        ...{ class: "form-header" },
    });
    /** @type {__VLS_StyleScopedClasses['form-header']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.h1, __VLS_intrinsics.h1)({
        ...{ class: "motto" },
    });
    /** @type {__VLS_StyleScopedClasses['motto']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.h1, __VLS_intrinsics.h1)({
        ...{ class: "motto" },
    });
    /** @type {__VLS_StyleScopedClasses['motto']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.h2, __VLS_intrinsics.h2)({
        ...{ class: "company-name" },
    });
    /** @type {__VLS_StyleScopedClasses['company-name']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.h3, __VLS_intrinsics.h3)({
        ...{ class: "form-subtitle-title" },
    });
    /** @type {__VLS_StyleScopedClasses['form-subtitle-title']} */ ;
    (__VLS_ctx.requestData?.askingStore?.name || '-');
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "date-row" },
    });
    /** @type {__VLS_StyleScopedClasses['date-row']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.span, __VLS_intrinsics.span)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    (__VLS_ctx.requestData.requestCode || __VLS_ctx.requestData.id);
    __VLS_asFunctionalElement1(__VLS_intrinsics.span, __VLS_intrinsics.span)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    (__VLS_ctx.formatDate(__VLS_ctx.requestData.requestedDate));
    __VLS_asFunctionalElement1(__VLS_intrinsics.table, __VLS_intrinsics.table)({
        ...{ class: "items-table" },
    });
    /** @type {__VLS_StyleScopedClasses['items-table']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.thead, __VLS_intrinsics.thead)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.tr, __VLS_intrinsics.tr)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.th, __VLS_intrinsics.th)({
        ...{ style: {} },
    });
    __VLS_asFunctionalElement1(__VLS_intrinsics.tbody, __VLS_intrinsics.tbody)({});
    if (!__VLS_ctx.requestData.items || __VLS_ctx.requestData.items.length === 0) {
        __VLS_asFunctionalElement1(__VLS_intrinsics.tr, __VLS_intrinsics.tr)({});
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({
            colspan: "10",
            ...{ class: "no-items" },
        });
        /** @type {__VLS_StyleScopedClasses['no-items']} */ ;
    }
    for (const [item, index] of __VLS_vFor((__VLS_ctx.requestData.items))) {
        __VLS_asFunctionalElement1(__VLS_intrinsics.tr, __VLS_intrinsics.tr)({
            key: (index),
        });
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (index + 1);
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({
            ...{ class: "text-left" },
        });
        /** @type {__VLS_StyleScopedClasses['text-left']} */ ;
        (__VLS_ctx.getItemName(item.itemId));
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (__VLS_ctx.getItemUOM(item.itemId) || 'Pcs');
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({
            ...{ class: "font-bold" },
        });
        /** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
        (item.quantity);
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (__VLS_ctx.getItemBrand(item.itemId) || '-');
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (__VLS_ctx.stripHtml(__VLS_ctx.getItemSpecification(item.itemId)) || '-');
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (__VLS_ctx.getItemModel(item.itemId) || '-');
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        __VLS_asFunctionalElement1(__VLS_intrinsics.td, __VLS_intrinsics.td)({});
        (item.remark || '-');
        // @ts-ignore
        [requestData, requestData, requestData, requestData, requestData, requestData, requestData, requestData, requestData, loading, goBack, printPage, formatDate, getItemName, getItemUOM, getItemBrand, stripHtml, getItemSpecification, getItemModel,];
    }
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "meta-grid" },
    });
    /** @type {__VLS_StyleScopedClasses['meta-grid']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "meta-col" },
    });
    /** @type {__VLS_StyleScopedClasses['meta-col']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-header text-center" },
    });
    /** @type {__VLS_StyleScopedClasses['block-header']} */ ;
    /** @type {__VLS_StyleScopedClasses['text-center']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-body dept-body" },
    });
    /** @type {__VLS_StyleScopedClasses['block-body']} */ ;
    /** @type {__VLS_StyleScopedClasses['dept-body']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    (__VLS_ctx.getStoreName(__VLS_ctx.requestData.askingStoreId));
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "meta-col" },
    });
    /** @type {__VLS_StyleScopedClasses['meta-col']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-header text-center" },
    });
    /** @type {__VLS_StyleScopedClasses['block-header']} */ ;
    /** @type {__VLS_StyleScopedClasses['text-center']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-body workflow-body" },
    });
    /** @type {__VLS_StyleScopedClasses['block-body']} */ ;
    /** @type {__VLS_StyleScopedClasses['workflow-body']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    (__VLS_ctx.getRequesterName());
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "meta-col" },
    });
    /** @type {__VLS_StyleScopedClasses['meta-col']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-header text-center" },
    });
    /** @type {__VLS_StyleScopedClasses['block-header']} */ ;
    /** @type {__VLS_StyleScopedClasses['text-center']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "block-body workflow-body" },
    });
    /** @type {__VLS_StyleScopedClasses['block-body']} */ ;
    /** @type {__VLS_StyleScopedClasses['workflow-body']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "footer-sections" },
    });
    /** @type {__VLS_StyleScopedClasses['footer-sections']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "input-row" },
    });
    /** @type {__VLS_StyleScopedClasses['input-row']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "gray-label" },
    });
    /** @type {__VLS_StyleScopedClasses['gray-label']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "lines-container" },
    });
    /** @type {__VLS_StyleScopedClasses['lines-container']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "reason-content-text" },
    });
    /** @type {__VLS_StyleScopedClasses['reason-content-text']} */ ;
    (__VLS_ctx.requestData.remark || '');
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "input-row short-width" },
    });
    /** @type {__VLS_StyleScopedClasses['input-row']} */ ;
    /** @type {__VLS_StyleScopedClasses['short-width']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "gray-label" },
    });
    /** @type {__VLS_StyleScopedClasses['gray-label']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "lines-container" },
    });
    /** @type {__VLS_StyleScopedClasses['lines-container']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "write-line" },
    });
    /** @type {__VLS_StyleScopedClasses['write-line']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "write-line" },
    });
    /** @type {__VLS_StyleScopedClasses['write-line']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "checked-by-section" },
    });
    /** @type {__VLS_StyleScopedClasses['checked-by-section']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "gray-label inline-label" },
    });
    /** @type {__VLS_StyleScopedClasses['gray-label']} */ ;
    /** @type {__VLS_StyleScopedClasses['inline-label']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "checked-by-body" },
    });
    /** @type {__VLS_StyleScopedClasses['checked-by-body']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.strong, __VLS_intrinsics.strong)({});
}
else if (__VLS_ctx.loading) {
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "loading-state" },
    });
    /** @type {__VLS_StyleScopedClasses['loading-state']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "spinner" },
    });
    /** @type {__VLS_StyleScopedClasses['spinner']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
}
else {
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "error-state" },
    });
    /** @type {__VLS_StyleScopedClasses['error-state']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.div, __VLS_intrinsics.div)({
        ...{ class: "error-icon" },
    });
    /** @type {__VLS_StyleScopedClasses['error-icon']} */ ;
    __VLS_asFunctionalElement1(__VLS_intrinsics.h2, __VLS_intrinsics.h2)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.p, __VLS_intrinsics.p)({});
    __VLS_asFunctionalElement1(__VLS_intrinsics.button, __VLS_intrinsics.button)({
        ...{ onClick: (__VLS_ctx.goBack) },
        ...{ class: "btn-back" },
    });
    /** @type {__VLS_StyleScopedClasses['btn-back']} */ ;
}
// @ts-ignore
[requestData, requestData, loading, goBack, getStoreName, getRequesterName,];
const __VLS_export = (await import('vue')).defineComponent({});
export default {};
