<!-- views/storemanagement/storebalance/print-balance.vue - COMPLETE FIXED FILE -->
<template>
  <!-- ================================================================ -->
  <!-- SCREEN VIEW - Print Button -->
  <!-- ================================================================ -->
  <div class="no-print" style="padding:20px; text-align:center; background:#f8fafc;">
    <button class="btn-back" @click="goBack" style="margin-right:10px; padding:8px 20px; cursor:pointer; background:#f1f5f9; border:1px solid #e2e8f0; border-radius:6px;">← Back to Store Balance</button>
    <button class="btn-print" @click="printPage" style="padding:8px 20px; background:#2563eb; color:white; border:none; border-radius:6px; cursor:pointer;">🖨️ Print Report</button>
  </div>

  <!-- ================================================================ -->
  <!-- PRINT CONTENT - ONLY THIS PRINTS -->
  <!-- ================================================================ -->
  <div id="print-area">
    <div v-if="balanceData">
      <!-- Header -->
      <div class="print-header">
        <h1 class="motto">WE TRUST IN GOD!!!</h1>
        <h1 class="motto">እግዚአብሔር ይባረክ!!!</h1>
        <h2 class="company">SUPER DOUBLE "T" GENERAL TRADING PLC .</h2>
        <h3 class="report-title">STORE BALANCE REPORT</h3>
        
        <div class="report-meta">
          <span><strong>Report Date:-</strong> {{ formatDateTime(new Date()) }}</span>
          <span><strong>Generated By:-</strong> {{ userDisplayName }}</span>
        </div>

        <!-- Summary -->
        <div class="print-summary">
          <div class="summary-item">
            <span class="label">🏪 STORE</span>
            <span class="value">{{ storeSummary }}</span>
          </div>
          <div class="summary-item">
            <span class="label">👥 GROUP</span>
            <span class="value">{{ groupSummary }}</span>
          </div>
          <div class="summary-item">
            <span class="label">📁 CATEGORY</span>
            <span class="value">{{ categorySummary }}</span>
          </div>
          <div class="summary-item">
            <span class="label">📦 TOTAL ITEMS</span>
            <span class="value">{{ balanceData.length }}</span>
          </div>
        </div>
      </div>

      <!-- Table - ALL DATA WILL PRINT -->
      <table class="print-table">
        <thead>
          <tr>
            <th style="width:5%;">#</th>
            <th style="width:12%;">Item Code</th>
            <th style="width:28%;">Item Name</th>
            <th style="width:15%;">Category</th>
            <th style="width:8%;">UOM</th>
            <th style="width:15%;">Balance</th>
            <th style="width:12%;">Status</th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="!balanceData || balanceData.length === 0">
            <td colspan="7" class="no-data">No balance records found</td>
          </tr>
          <tr v-for="(item, index) in balanceData" :key="item.id">
            <td class="text-center">{{ index + 1 }}</td>
            <td>{{ item.itemCode || getItemCode(item.itemId) }}</td>
            <td class="text-left">
              <div class="item-name">
                <div class="common-name">{{ item.itemCommonName || getItemCommonName(item.itemId) || 'Unnamed' }}</div>
                <div class="standard-name" v-if="item.itemStandardName || getItemStandardName(item.itemId)">
                  {{ item.itemStandardName || getItemStandardName(item.itemId) }}
                </div>
              </div>
            </td>
            <td>
              <span class="category-badge">{{ item.categoryName || 'Uncategorized' }}</span>
            </td>
            <td>{{ item.uomCode || getItemUnit(item.itemId) }}</td>
            <td class="text-right">{{ formatNumber(item.balance) }}</td>
            <td>
              <span :class="['status-badge', (item.status || 'inactive').toLowerCase()]">
                {{ item.status || 'Inactive' }}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Loading -->
    <div v-else-if="loading" class="loading-state">
      <div class="spinner"></div>
      <p>Loading balance data...</p>
    </div>

    <!-- Error -->
    <div v-else class="error-state">
      <div class="error-icon">📊</div>
      <h2>No Data Available</h2>
      <p>No store balance data found to display.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import balanceService from '@/stores/balanceService'

// ================================================================
// STATE
// ================================================================

const router = useRouter()
const route = useRoute()
const loading = ref(true)
const balanceData = ref<any[]>([])
const stores = ref<any[]>([])
const groups = ref<any[]>([])
const categories = ref<any[]>([])
const inventoryItems = ref<any[]>([])

// Get user data
const getUserData = () => {
  try {
    const data = JSON.parse(localStorage.getItem('user') || '{}')
    return data
  } catch (error) {
    console.error('Error parsing user data:', error)
    return {}
  }
}

const userData = ref(getUserData())
const userDisplayName = computed(() => {
  return userData.value?.fullName || userData.value?.username || 'User'
})

// Filter params from query
const filterStore = ref(route.query.storeId || '')
const filterGroup = ref(route.query.groupId || '')
const filterCategory = ref(route.query.categoryId || '')
const filterStatus = ref(route.query.status || '')

// ================================================================
// COMPUTED
// ================================================================

const storeSummary = computed(() => {
  if (!balanceData.value || balanceData.value.length === 0) return 'No stores'
  const storeNames = new Set()
  balanceData.value.forEach(item => {
    const name = item.storeName || getStoreName(item.storeId)
    if (name) storeNames.add(name)
  })
  return Array.from(storeNames).join(', ') || 'No stores'
})

const groupSummary = computed(() => {
  if (!balanceData.value || balanceData.value.length === 0) return 'No groups'
  const groupNames = new Set()
  balanceData.value.forEach(item => {
    const name = item.groupName || getGroupName(item.groupId)
    if (name) groupNames.add(name)
  })
  return Array.from(groupNames).join(', ') || 'No groups'
})

const categorySummary = computed(() => {
  if (!balanceData.value || balanceData.value.length === 0) return 'No categories'
  const categoryNames = new Set()
  balanceData.value.forEach(item => {
    const name = item.categoryName || getCategoryName(item.categoryId)
    if (name) categoryNames.add(name)
  })
  return Array.from(categoryNames).join(', ') || 'No categories'
})

// ================================================================
// METHODS
// ================================================================

const loadStores = async () => {
  try {
    const response = await balanceService.getStores()
    stores.value = response.data || []
  } catch (error) {
    console.error('Load stores error:', error)
  }
}

const loadGroups = async () => {
  try {
    const response = await balanceService.getGroups()
    groups.value = response.data || []
  } catch (error) {
    console.error('Load groups error:', error)
  }
}

const loadCategories = async () => {
  try {
    const response = await balanceService.getActiveCategories()
    if (response.success) {
      categories.value = response.data || []
    }
  } catch (error) {
    console.error('Load categories error:', error)
  }
}

const loadItems = async () => {
  try {
    const response = await balanceService.getActiveItems()
    inventoryItems.value = response.data || []
  } catch (error) {
    console.error('Load items error:', error)
  }
}

const loadBalances = async () => {
  try {
    const filters: any = {}
    if (filterStore.value) filters.storeId = Number(filterStore.value)
    if (filterGroup.value) filters.groupId = Number(filterGroup.value)
    if (filterCategory.value) filters.categoryId = Number(filterCategory.value)
    if (filterStatus.value) filters.status = filterStatus.value
    filters.limit = 10000 // ✅ Get ALL data for print
    
    const response = await balanceService.getBalances(filters)
    balanceData.value = response.data || []
  } catch (error) {
    console.error('Load balances error:', error)
  } finally {
    loading.value = false
  }
}

// -- Helper Methods --
const getStoreName = (storeId: number): string => {
  if (!storeId) return 'Unknown'
  const balance = balanceData.value.find(b => b.storeId === storeId)
  if (balance) return balance.storeName || 'Unknown'
  const store = stores.value.find(s => s.id === storeId)
  return store ? store.name : 'Unknown'
}

const getGroupName = (groupId: number): string => {
  if (!groupId) return 'Unknown'
  const balance = balanceData.value.find(b => b.groupId === groupId)
  if (balance) return balance.groupName || 'Unknown'
  const group = groups.value.find(g => g.id === groupId)
  return group ? group.name : 'Unknown'
}

const getCategoryName = (categoryId: number): string => {
  if (!categoryId) return 'Uncategorized'
  const balance = balanceData.value.find(b => b.categoryId === categoryId)
  if (balance) return balance.categoryName || 'Uncategorized'
  const category = categories.value.find(c => c.id === categoryId)
  return category ? category.name : 'Uncategorized'
}

const getItemStandardName = (itemId: number): string => {
  if (!itemId) return ''
  const balance = balanceData.value.find(b => b.itemId === itemId)
  if (balance) return balance.itemStandardName || ''
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.standardName || '' : ''
}

const getItemCommonName = (itemId: number): string => {
  if (!itemId) return 'Unnamed'
  const balance = balanceData.value.find(b => b.itemId === itemId)
  if (balance) return balance.itemCommonName || balance.itemName || 'Unnamed'
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? (item.name || item.standardName || 'Unnamed') : 'Unnamed'
}

const getItemCode = (itemId: number): string => {
  if (!itemId) return 'N/A'
  const balance = balanceData.value.find(b => b.itemId === itemId)
  if (balance) return balance.itemCode || 'N/A'
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.code : 'N/A'
}

const getItemUnit = (itemId: number): string => {
  if (!itemId) return ''
  const balance = balanceData.value.find(b => b.itemId === itemId)
  if (balance) return balance.uomCode || ''
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.uomCode || '' : ''
}

const formatNumber = (num: number): string => {
  if (num === undefined || num === null) return '0'
  return new Intl.NumberFormat().format(num)
}

const formatDateTime = (date: Date): string => {
  return date.toLocaleString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })
}

// -- Navigation --
const goBack = (): void => {
  router.push('/store-balance')
}

// ✅ FIXED: Give Vue time to render before printing
const printPage = (): void => {
  setTimeout(() => {
    window.print()
  }, 500)
}

// ================================================================
// LIFECYCLE
// ================================================================

onMounted(async () => {
  await Promise.all([
    loadStores(),
    loadGroups(),
    loadCategories(),
    loadItems()
  ])
  await loadBalances()
})
</script>

<style scoped>
/* ================================================================ */
/* SCREEN STYLES - SCOPED */
/* ================================================================ */
.no-print {
  display: block;
}

.btn-back {
  background: #f1f5f9;
  color: #1e293b;
  border: 1px solid #e2e8f0;
  padding: 8px 18px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
}

.btn-print {
  background: #2563eb;
  color: white;
  border: none;
  padding: 8px 18px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
}

/* ================================================================
   PRINT HEADER
   ================================================================ */
.print-header {
  margin-bottom: 20px;
}

.motto {
  text-align: center;
  font-family: 'Georgia', serif;
  font-size: 18px;
  font-weight: 900;
  letter-spacing: 1px;
  margin: 0 0 2px 0;
}

.company {
  text-align: center;
  font-size: 20px;
  font-weight: 800;
  margin: 4px 0 4px 0;
}

.report-title {
  text-align: center;
  font-size: 16px;
  font-weight: bold;
  letter-spacing: 0.5px;
  text-transform: uppercase;
  margin: 0 0 12px 0;
  color: #1a1a1a;
}

.report-meta {
  display: flex;
  justify-content: space-between;
  font-size: 13px;
  margin-bottom: 12px;
  padding: 6px 0;
  border-top: 1px solid #ddd;
  border-bottom: 1px solid #ddd;
}

/* ================================================================
   PRINT SUMMARY
   ================================================================ */
.print-summary {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  gap: 12px;
  margin-bottom: 16px;
  padding: 12px 16px;
  background: #f0f2f5;
  border-radius: 6px;
  border: 1px solid #d1d5db;
}

.summary-item {
  display: flex;
  flex-direction: column;
  text-align: center;
}

.summary-item .label {
  font-size: 12px;
  font-weight: 700;
  color: #1a1a2e;
  text-transform: uppercase;
  letter-spacing: 0.3px;
  margin-bottom: 2px;
}

.summary-item .value {
  font-size: 14px;
  font-weight: 600;
  color: #0f172a;
  background: white;
  padding: 2px 8px;
  border-radius: 4px;
  border: 1px solid #e2e8f0;
}

/* ================================================================
   PRINT TABLE
   ================================================================ */
.print-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
  margin-bottom: 10px;
}

.print-table th,
.print-table td {
  border: 1px solid #7f7f7f;
  padding: 5px 8px;
  text-align: center;
}

.print-table th {
  background: #e6e6e6;
  font-weight: bold;
  font-size: 12px;
}

.print-table td.text-left {
  text-align: left;
}

.print-table td.text-right {
  text-align: right;
}

.print-table td.text-center {
  text-align: center;
}

.no-data {
  padding: 30px !important;
  color: #7f7f7f;
  font-style: italic;
  text-align: center;
}

/* ================================================================
   ITEM NAME
   ================================================================ */
.item-name {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.common-name {
  font-size: 13px;
  font-weight: 600;
  color: #1e293b;
}

.standard-name {
  font-size: 11px;
  color: #64748b;
  font-style: italic;
}

/* ================================================================
   CATEGORY BADGE
   ================================================================ */
.category-badge {
  display: inline-block;
  padding: 1px 10px;
  border-radius: 10px;
  font-size: 11px;
  font-weight: 500;
  background: #e0e7ff;
  color: #4338ca;
}

/* ================================================================
   STATUS BADGE
   ================================================================ */
.status-badge {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 12px;
  font-size: 10px;
  font-weight: 500;
}

.status-badge.active {
  background: #dcfce7;
  color: #166534;
}

.status-badge.inactive {
  background: #fee2e2;
  color: #991b1b;
}

/* ================================================================
   LOADING & ERROR
   ================================================================ */
.loading-state, .error-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 300px;
}

.spinner {
  border: 4px solid #f3f4f6;
  border-top: 4px solid #2563eb;
  border-radius: 50%;
  width: 35px;
  height: 35px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.error-icon {
  font-size: 48px;
  opacity: 0.5;
  margin-bottom: 12px;
}

.error-state h2 {
  color: #1e293b;
  margin-bottom: 8px;
}

.error-state p {
  color: #64748b;
  margin-bottom: 16px;
}
</style>

<style>
/* ================================================================ */
/* ✅ GLOBAL PRINT STYLES - NON-SCOPED                            */
/* ================================================================ */
@media print {
  /* Reset body for clean print */
  html,
  body {
    margin: 0 !important;
    padding: 0 !important;
    background: #fff !important;
    height: auto !important;
    overflow: visible !important;
  }

  /* Hide everything by default */
  body * {
    visibility: hidden !important;
  }

  /* Only show the print area */
  #print-area,
  #print-area * {
    visibility: visible !important;
  }

  /* Position the print area - NO HEIGHT RESTRICTIONS */
  #print-area {
    position: absolute !important;
    left: 0 !important;
    top: 0 !important;
    width: 100% !important;
    max-width: 100% !important;
    padding: 10mm !important;
    margin: 0 !important;
    background: white !important;
    height: auto !important;
    min-height: auto !important;
    overflow: visible !important;
    display: block !important;
  }

  /* ✅ Ensure the table container doesn't restrict height */
  #print-area > div {
    height: auto !important;
    min-height: auto !important;
    overflow: visible !important;
    display: block !important;
  }

  /* Hide all UI elements */
  .no-print {
    display: none !important;
  }

  /* Table styles for clean printing - ALL ROWS WILL PRINT */
  table {
    width: 100% !important;
    border-collapse: collapse !important;
    page-break-inside: auto !important;
    display: table !important;
  }

  thead {
    display: table-header-group !important;
  }

  tbody {
    display: table-row-group !important;
  }

  tfoot {
    display: table-footer-group !important;
  }

  tr {
    page-break-inside: avoid !important;
    page-break-after: auto !important;
    display: table-row !important;
  }

  td,
  th {
    border: 1px solid #000 !important;
    padding: 5px !important;
    font-size: 11px !important;
    display: table-cell !important;
  }

  th {
    background: #e5e5e5 !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  /* Keep header together */
  .print-header {
    page-break-after: avoid !important;
    margin-bottom: 15px !important;
  }

  /* Page settings */
  @page {
    size: A4 portrait;
    margin: 12mm;
  }

  /* Summary box colors */
  .print-summary {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  .status-badge.active {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  .status-badge.inactive {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  .category-badge {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  /* ✅ Prevent any element from restricting height */
  .print-table,
  .print-table tbody,
  .print-table tr {
    height: auto !important;
    min-height: auto !important;
    max-height: none !important;
  }
}
</style>`