<template>
  <div class="report-page">

    <!-- Report Frame -->
    <div class="report-container">

      <!-- Header -->
      <div class="report-header">

        <div class="logo-box">
          <img src="@/assets/image.png" alt="Company Logo" />
        </div>

        <div class="company-info">
          <h2>SUPER DOUBLE T GENERAL TRADING PLC</h2>
          <p class="tagline">እግዚአብሔር ይባረክ</p>
        </div>

        <div class="report-meta">
          <p class="title">OFFICIAL REPORT</p>
          <p class="date">Date: {{ today }}</p>
        </div>

      </div>

      <!-- Divider -->
      <div class="divider"></div>

      <!-- Body -->
      <div class="report-body">
        <slot>
          <p class="empty">No report data passed yet.</p>
        </slot>
      </div>

      <!-- Footer -->
      <div class="report-footer">
        Generated by SUPER DOUBLE T GENERAL TRADING PLC System
      </div>

    </div>

    <!-- Print Button -->
    <button class="print-btn" @click="printPage">
      Print Report
    </button>

  </div>
</template>

<script setup>
import { computed } from "vue"

const today = computed(() =>
  new Date().toLocaleDateString()
)

const printPage = () => {
  window.print()
}
</script>

<style scoped>

/* PAGE */
.report-page {
  padding: 18px;
  background: #f4f4f4;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
}

/* FRAME */
.report-container {
  width: 100%;
  max-width: 900px;
  background: #fff;
  border: 2px solid #000;
  box-shadow: 0 18px 40px rgba(0,0,0,0.15);
  padding: 20px;
  position: relative;
}

/* GOLD ACCENT LINE */
.report-container::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  height: 5px;
  width: 100%;
  background: linear-gradient(90deg, #000, #f5c400, #000);
}

/* HEADER (COMPACT + PREMIUM) */
.report-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 6px 0;
}

/* LOGO */
.logo-box img {
  width: 75px;
  height: 75px;
  object-fit: contain;
  
  padding: 3px;
  background: #fff;
}

/* COMPANY */
.company-info {
  text-align: center;
  flex: 1;
}

.company-info h2 {
  margin: 0;
  font-size: 27px;   /* ⬅ increased from 14px */
  font-weight: 900;
  color: #000;
  letter-spacing: 0.5px;
}

.tagline {
  margin: 4px 0 0;
  font-size: 23px;        /* ⬅ increased */
  font-weight: 800;       /* bold */
  color: #000;
  background: linear-gradient(90deg, #000, #f5c400, #000);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  letter-spacing: 0.3px;
}

/* META */
.report-meta {
  text-align: right;
  font-size: 11px;
  color: #333;
  line-height: 1.3;
}

.report-meta .title {
  font-weight: 800;
  color: #f5c400;
  letter-spacing: 0.5px;
}

.report-meta .date {
  font-size: 11px;
  color: #444;
}

/* DIVIDER */
.divider {
  margin: 10px 0;
  height: 2px;
  background: linear-gradient(90deg, #000, #f5c400, #000);
  opacity: 0.8;
}

/* BODY */
.report-body {
  min-height: 320px;
  padding: 10px 0;
}

/* EMPTY STATE */
.empty {
  text-align: center;
  color: #aaa;
  font-size: 13px;
}

/* FOOTER */
.report-footer {
  margin-top: 18px;
  text-align: center;
  font-size: 11px;
  color: #777;
  border-top: 1px dashed #ddd;
  padding-top: 10px;
}

/* PRINT BUTTON */
.print-btn {
  margin-top: 16px;
  padding: 10px 18px;
  background: #f5c400;
  color: #000;
  border: none;
  font-weight: 700;
  border-radius: 8px;
  cursor: pointer;
  transition: 0.2s;
}

.print-btn:hover {
  background: #e0b800;
  transform: translateY(-1px);
}

/* PRINT MODE */
@media print {
  .print-btn {
    display: none;
  }

  .report-page {
    background: white;
    padding: 0;
  }

  .report-container {
    box-shadow: none;
    border: none;
  }
}

</style>