<!-- views/storemanagement/storetransaction/print-transactions.vue - COMPLETE WITH CATEGORY SUPPORT -->

<template>
  <div class="top-actions no-print" v-if="transactionData || !loading">
    <button class="btn-back-top" @click="goBack">← Back to Transactions</button>
    <button class="btn-print-top" @click="printPage">🖨️ Print Report</button>
  </div>

  <div class="print-page" v-if="transactionData">
    <header class="form-header">
      <h1 class="motto">WE TRUST IN GOD!!!</h1>
      <h1 class="motto">እግዚአብሔር ይባረክ!!!</h1>

      <h2 class="company-name">SUPER DOUBLE "T" GENERAL TRADING PLC .</h2>
      <h3 class="form-subtitle-title">STORE TRANSACTION REPORT</h3>
      
      <div class="date-row">
        <span><strong>Report Date:-</strong> {{ formatDateTime(new Date()) }}</span>
        <span><strong>Generated By:-</strong> {{ userDisplayName }}</span>
      </div>

      <!-- ✅ STORE, GROUP, CATEGORY SUMMARY HEADER -->
      <div class="store-group-category-summary">
        <div class="summary-item">
          <span class="summary-label">🏪 STORE</span>
          <span class="summary-value">{{ storeSummary }}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">👥 GROUP</span>
          <span class="summary-value">{{ groupSummary }}</span>
        </div>
        
      
        <div class="summary-item">
          <span class="summary-label">📦 TOTAL</span>
          <span class="summary-value">{{ transactionData.length }}</span>
        </div>
      </div>
      
    

      <!-- ✅ TRANSACTION STATS -->
      <div class="transaction-stats">
        <div class="stat-item stock-in">
          <span class="stat-icon">📥</span>
          <span class="stat-label">Stock In</span>
          <span class="stat-value">{{ totalStockIn }}</span>
        </div>
        <div class="stat-item stock-out">
          <span class="stat-icon">📤</span>
          <span class="stat-label">Stock Out</span>
          <span class="stat-value">{{ totalStockOut }}</span>
        </div>
        <div class="stat-item total">
          <span class="stat-icon">📊</span>
          <span class="stat-label">Total</span>
          <span class="stat-value">{{ transactionData.length }}</span>
        </div>
      </div>
    </header>

    <table class="items-table">
      <thead>
        <tr>
          <th style="width: 4%;">#</th>
          <th style="width: 12%;">Date</th>
          <th style="width: 8%;">Type</th>
          <th style="width: 10%;">Item Code</th>
          <th style="width: 25%;">Item</th>
          <th style="width: 12%;">Category</th>
          <th style="width: 8%;">UOM</th>
          <th style="width: 10%;">Qty</th>
          <th style="width: 11%;">Reference</th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="!transactionData || transactionData.length === 0">
          <td colspan="9" class="no-items">No transactions found</td>
        </tr>
        <tr v-for="(transaction, index) in paginatedData" :key="transaction.id">
          <td>{{ (currentPage - 1) * pageSize + index + 1 }}</td>
          <td class="date-cell">{{ formatDateShort(transaction.createdAt) }}</td>
          <td>
            <span :class="['type-badge', transaction.type === 'Stock In' ? 'stock-in' : 'stock-out']">
              {{ transaction.type === 'Stock In' ? '📥' : '📤' }}
            </span>
          </td>
          <td class="item-code">{{ transaction.itemCode || getItemCode(transaction.itemId) }}</td>
          <td class="text-left">
            <div class="item-info">
              <!-- ✅ COMMON NAME - Primary (always shown) -->
              <div class="item-common-name">{{ transaction.itemCommonName || getItemCommonName(transaction.itemId) || 'Unnamed' }}</div>
              <!-- ✅ STANDARD NAME - Secondary (only shown if exists) -->
              <div class="item-standard-name" v-if="transaction.itemStandardName || getItemStandardName(transaction.itemId)">
                {{ transaction.itemStandardName || getItemStandardName(transaction.itemId) }}
              </div>
            </div>
          </td>
          <td>
            <span class="category-tag" :class="transaction.categoryName ? 'has-category' : 'no-category'">
              {{ transaction.categoryName || 'Uncategorized' }}
            </span>
          </td>
          <td>{{ transaction.uomCode || getItemUnit(transaction.itemId) }}</td>
          <td>
            <span :class="['quantity-value', transaction.type === 'Stock In' ? 'positive' : 'negative']">
              {{ transaction.type === 'Stock In' ? '+' : '-' }}{{ formatNumber(transaction.quantity) }}
            </span>
          </td>
          <td class="reference-cell">{{ transaction.referenceType || '-' }}</td>
        </tr>
      </tbody>
    </table>

    <!-- Pagination for print view -->
    <div class="pagination no-print" v-if="transactionData && transactionData.length > pageSize">
      <button class="page-btn" :disabled="currentPage === 1" @click="changePage(currentPage - 1)">
        ← Previous
      </button>
      <span class="page-info">Page {{ currentPage }} of {{ totalPages }}</span>
      <button class="page-btn" :disabled="currentPage === totalPages" @click="changePage(currentPage + 1)">
        Next →
      </button>
      <select v-model="pageSize" @change="changePageSize" class="limit-select">
        <option :value="10">10 per page</option>
        <option :value="20">20 per page</option>
        <option :value="50">50 per page</option>
        <option :value="100">100 per page</option>
      </select>
    </div>

   
  </div>

  <div v-else-if="loading" class="loading-state">
    <div class="spinner"></div>
    <p>Loading transaction data...</p>
  </div>

  <div v-else class="error-state">
    <div class="error-icon">📊</div>
    <h2>No Data Available</h2>
    <p>No transaction data found to display.</p>
    <button class="btn-back" @click="goBack">← Back to Transactions</button>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import transactionService from '@/stores/transactionService'
import balanceService from '@/stores/balanceService'

// ================================================================
// STATE
// ================================================================

const router = useRouter()
const route = useRoute()
const loading = ref(true)
const transactionData = ref<any[]>([])
const stores = ref<any[]>([])
const groups = ref<any[]>([])
const categories = ref<any[]>([])  // ✅ ADD CATEGORIES
const inventoryItems = ref<any[]>([])
const currentPage = ref(1)
const pageSize = ref(20)

// Get user data
const getUserData = () => {
  try {
    const data = JSON.parse(localStorage.getItem('user') || '{}')
    return data
  } catch (error) {
    console.error('Error parsing user data:', error)
    return {}
  }
}

const userData = ref(getUserData())
const userDisplayName = computed(() => {
  return userData.value?.fullName || userData.value?.username || 'User'
})

// Filter params from query
const filterStore = ref<string>(typeof route.query.storeId === 'string' ? route.query.storeId : '')
const filterGroup = ref<string>(typeof route.query.groupId === 'string' ? route.query.groupId : '')
const filterCategory = ref<string>(typeof route.query.categoryId === 'string' ? route.query.categoryId : '')  // ✅ ADD CATEGORY
const filterItem = ref<string>(typeof route.query.itemId === 'string' ? route.query.itemId : '')
const filterType = ref<string>(typeof route.query.type === 'string' ? route.query.type : '')
const filterDate = ref<string>(typeof route.query.date === 'string' ? route.query.date : '')
const searchQuery = ref<string>(typeof route.query.search === 'string' ? route.query.search : '')

// ================================================================
// COMPUTED
// ================================================================

const totalStockIn = computed(() => {
  if (!transactionData.value) return 0
  return transactionData.value.filter(t => t.type === 'Stock In').length
})

const totalStockOut = computed(() => {
  if (!transactionData.value) return 0
  return transactionData.value.filter(t => t.type === 'Stock Out').length
})

const totalPages = computed(() => {
  if (!transactionData.value) return 1
  return Math.ceil(transactionData.value.length / pageSize.value) || 1
})

const paginatedData = computed(() => {
  if (!transactionData.value) return []
  const start = (currentPage.value - 1) * pageSize.value
  const end = start + pageSize.value
  return transactionData.value.slice(start, end)
})

// ✅ STORE SUMMARY
const storeSummary = computed(() => {
  if (!transactionData.value || transactionData.value.length === 0) return 'No stores'
  const storeNames = new Set()
  transactionData.value.forEach(t => {
    const name = t.storeName || getStoreName(t.storeId)
    if (name) storeNames.add(name)
  })
  return Array.from(storeNames).join(', ') || 'No stores'
})

// ✅ GROUP SUMMARY
const groupSummary = computed(() => {
  if (!transactionData.value || transactionData.value.length === 0) return 'No groups'
  const groupNames = new Set()
  transactionData.value.forEach(t => {
    const name = t.groupName || getGroupName(t.groupId)
    if (name) groupNames.add(name)
  })
  return Array.from(groupNames).join(', ') || 'No groups'
})

// ✅ CATEGORY SUMMARY
const categorySummary = computed(() => {
  if (!transactionData.value || transactionData.value.length === 0) return 'No categories'
  const categoryNames = new Set()
  transactionData.value.forEach(t => {
    const name = t.categoryName || getCategoryName(t.categoryId)
    if (name) categoryNames.add(name)
  })
  return Array.from(categoryNames).join(', ') || 'No categories'
})

// ✅ TRANSACTION TYPE SUMMARY
const transactionTypeSummary = computed(() => {
  if (!transactionData.value || transactionData.value.length === 0) return 'All Types'
  const types = new Set()
  transactionData.value.forEach(t => {
    types.add(t.type)
  })
  return Array.from(types).join(', ') || 'All Types'
})

// ================================================================
// METHODS
// ================================================================

const loadStores = async () => {
  try {
    const response = await balanceService.getStores()
    stores.value = response.data || []
  } catch (error) {
    console.error('Load stores error:', error)
  }
}

const loadGroups = async () => {
  try {
    const response = await balanceService.getGroups()
    groups.value = response.data || []
  } catch (error) {
    console.error('Load groups error:', error)
  }
}

// ✅ LOAD CATEGORIES
const loadCategories = async () => {
  try {
    const response = await balanceService.getActiveCategories()
    if (response.success) {
      categories.value = response.data || []
      console.log(`✅ Loaded ${categories.value.length} categories for print`)
    }
  } catch (error) {
    console.error('Load categories error:', error)
  }
}

const loadItems = async () => {
  try {
    const response = await balanceService.getActiveItems()
    inventoryItems.value = response.data || []
  } catch (error) {
    console.error('Load items error:', error)
  }
}

const loadTransactions = async () => {
  try {
    const filters: any = {}
    
    if (filterStore.value) {
      filters.storeId = Number(filterStore.value)
    }
    if (filterGroup.value) {
      filters.groupId = Number(filterGroup.value)
    }
    // ✅ ADD CATEGORY FILTER
    if (filterCategory.value) {
      filters.categoryId = Number(filterCategory.value)
    }
    if (filterItem.value) {
      filters.itemId = Number(filterItem.value)
    }
    if (filterType.value) {
      filters.transactionType = filterType.value
    }
    if (searchQuery.value) {
      filters.search = searchQuery.value
    }
    
    filters.limit = 1000 // Get all data for print
    
    const response = await transactionService.getTransactions(filters)
    transactionData.value = response.data || []
  } catch (error) {
    console.error('Load transactions error:', error)
  } finally {
    loading.value = false
  }
}

// -- Helper Methods --
const getStoreName = (storeId: number): string => {
  if (!storeId) return 'Unknown'
  const store = stores.value.find(s => s.id === storeId)
  return store ? store.name : 'Unknown'
}

const getGroupName = (groupId: number): string => {
  if (!groupId) return 'Unknown'
  const group = groups.value.find(g => g.id === groupId)
  return group ? group.name : 'Unknown'
}

// ✅ GET CATEGORY NAME
const getCategoryName = (categoryId: number): string => {
  if (!categoryId) return 'Uncategorized'
  const transaction = transactionData.value.find(t => t.categoryId === categoryId)
  if (transaction) return transaction.categoryName || 'Uncategorized'
  const category = categories.value.find(c => c.id === categoryId)
  return category ? category.name : 'Uncategorized'
}

// ✅ GET STANDARD NAME
const getItemStandardName = (itemId: number): string => {
  if (!itemId) return ''
  const transaction = transactionData.value.find(t => t.itemId === itemId)
  if (transaction) return transaction.itemStandardName || ''
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.standardName || '' : ''
}

// ✅ GET COMMON NAME (uses name as primary, standardName as fallback)
const getItemCommonName = (itemId: number): string => {
  if (!itemId) return 'Unnamed'
  const transaction = transactionData.value.find(t => t.itemId === itemId)
  if (transaction) return transaction.itemCommonName || 'Unnamed'
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? (item.name || item.standardName || 'Unnamed') : 'Unnamed'
}

const getItemName = (itemId: number): string => {
  return getItemCommonName(itemId)
}

const getItemCode = (itemId: number): string => {
  if (!itemId) return 'N/A'
  const transaction = transactionData.value.find(t => t.itemId === itemId)
  if (transaction) return transaction.itemCode || 'N/A'
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.code : 'N/A'
}

const getItemUnit = (itemId: number): string => {
  if (!itemId) return ''
  const transaction = transactionData.value.find(t => t.itemId === itemId)
  if (transaction) return transaction.uomCode || ''
  const item = inventoryItems.value.find(i => i.id === itemId)
  return item ? item.uomCode || item.uom?.code || '' : ''
}

const getDateLabel = (dateFilter: string): string => {
  const labels: Record<string, string> = {
    'today': 'Today',
    'yesterday': 'Yesterday',
    'week': 'This Week',
    'month': 'This Month',
    '3months': 'Last 3 Months',
    '6months': 'Last 6 Months',
    '12months': 'Last 12 Months'
  }
  return labels[dateFilter] || dateFilter
}

const formatNumber = (num: number): string => {
  if (num === undefined || num === null) return '0'
  return new Intl.NumberFormat().format(num)
}

const formatDateShort = (dateString?: string): string => {
  if (!dateString) return ''
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { 
    month: 'short', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatDateTime = (date: Date): string => {
  return date.toLocaleString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })
}

// -- Pagination --
const changePage = (page: number): void => {
  if (page < 1 || page > totalPages.value) return
  currentPage.value = page
}

const changePageSize = (): void => {
  currentPage.value = 1
}

// -- Navigation --
const goBack = (): void => {
  router.push('/store-transaction')
}

const printPage = (): void => { 
  window.print() 
}

// ================================================================
// LIFECYCLE
// ================================================================

onMounted(async () => {
  await Promise.all([
    loadStores(),
    loadGroups(),
    loadCategories(),  // ✅ ADD CATEGORIES
    loadItems()
  ])
  await loadTransactions()
})
</script>

<style scoped>
/* ================================================================
   PAGE SETUP & INTERACTIVE UI
   ================================================================ */
.print-page {
  font-family: 'Arial', sans-serif;
  color: #000;
  max-width: 1100px;
  margin: 0 auto;
  padding: 20px;
  background-color: #ffffff;
}

.top-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  max-width: 1100px;
  margin: 10px auto 20px auto;
  padding: 12px 16px;
  background: #f8fafc;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}

.btn-back-top {
  background: #f1f5f9;
  color: #1e293b;
  border: 1px solid #e2e8f0;
  padding: 8px 18px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
}

.btn-print-top {
  background: #2563eb;
  color: white;
  border: none;
  padding: 8px 18px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
}

/* ================================================================
   FORM COMPONENT TYPOGRAPHY & HEADERS
   ================================================================ */
.form-header {
  margin-bottom: 20px;
}

.motto {
  text-align: center;
  font-family: 'Georgia', serif;
  font-size: 19px;
  font-weight: 900;
  letter-spacing: 1px;
  margin: 0 0 4px 0;
}

.company-name {
  text-align: center;
  font-size: 21px;
  font-weight: 800;
  margin: 0 0 8px 0;
}

.form-subtitle-title {
  text-align: center;
  font-size: 16px;
  font-weight: bold;
  letter-spacing: 0.5px;
  text-transform: uppercase;
  margin: 0 0 15px 0;
  color: #1a1a1a;
}

.date-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 13px;
  margin-bottom: 12px;
  flex-wrap: wrap;
  gap: 8px;
}

/* ================================================================
   STORE, GROUP & CATEGORY SUMMARY HEADER
   ================================================================ */
.store-group-category-summary {
  display: grid;
  grid-template-columns: 1fr  1fr 1fr;
  gap: 12px;
  margin-bottom: 12px;
  padding: 14px 18px;
  background: #f0f2f5;
  border-radius: 8px;
  border: 2px solid #d1d5db;
}

.summary-item {
  display: flex;
  flex-direction: column;
  text-align: center;
}

.summary-label {
  font-size: 12px;
  font-weight: 800;
  color: #1a1a2e;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 4px;
}

.summary-value {
  font-size: 14px;
  font-weight: 700;
  color: #0f172a;
  margin-top: 2px;
  background: white;
  padding: 4px 12px;
  border-radius: 4px;
  border: 1px solid #e2e8f0;
  word-break: break-word;
}

/* ================================================================
   TRANSACTION STATS
   ================================================================ */
.transaction-stats {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 12px;
  margin-bottom: 16px;
  padding: 12px 16px;
  background: #f8fafc;
  border-radius: 8px;
  border: 1px solid #e2e8f0;
}

.stat-item {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 8px 12px;
  border-radius: 6px;
  background: white;
}

.stat-item.stock-in {
  border-left: 4px solid #22c55e;
}

.stat-item.stock-out {
  border-left: 4px solid #ef4444;
}

.stat-item.total {
  border-left: 4px solid #3b82f6;
}

.stat-icon {
  font-size: 18px;
}

.stat-label {
  font-size: 12px;
  font-weight: 600;
  color: #475569;
}

.stat-value {
  font-size: 16px;
  font-weight: 700;
  color: #1e293b;
  margin-left: auto;
}

/* ================================================================
   FILTER SUMMARY
   ================================================================ */
.filter-summary {
  margin-bottom: 12px;
  padding: 8px 12px;
  background: #f8fafc;
  border-radius: 6px;
  border: 1px solid #e2e8f0;
}

.filter-tags {
  display: flex;
  gap: 20px;
  flex-wrap: wrap;
}

.filter-tag {
  font-size: 13px;
  color: #1e293b;
}

/* ================================================================
   TABLE CONFIGURATION
   ================================================================ */
.items-table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 20px;
  font-size: 12px;
}

.items-table th, 
.items-table td {
  border: 1px solid #7f7f7f;
  padding: 6px 8px;
  text-align: center;
  height: 24px;
  word-wrap: break-word;
}

.items-table th {
  background-color: #e6e6e6;
  font-weight: bold;
  font-size: 12px;
}

.items-table td.text-left {
  text-align: left;
  padding-left: 8px;
}

.no-items {
  padding: 30px !important;
  color: #7f7f7f;
  font-style: italic;
  text-align: center;
}

.date-cell {
  font-size: 11px;
  white-space: nowrap;
}

.reference-cell {
  font-size: 11px;
  color: #64748b;
}

/* ================================================================
   ITEM INFO - UPDATED
   ================================================================ */
.item-info {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.item-code {
  font-weight: 600;
  color: #2563eb;
  font-size: 11px;
}

/* ✅ COMMON NAME - Primary (always shown) */
.item-common-name {
  font-size: 13px;
  font-weight: 600;
  color: #1e293b;
  line-height: 1.3;
}

/* ✅ STANDARD NAME - Secondary (only shown if exists) */
.item-standard-name {
  font-size: 11px;
  color: #64748b;
  font-weight: 400;
  font-style: italic;
  line-height: 1.2;
}

/* ================================================================
   CATEGORY TAG
   ================================================================ */
.category-tag {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 10px;
  font-size: 11px;
  font-weight: 500;
  white-space: nowrap;
}

.category-tag.has-category {
  background: #e0e7ff;
  color: #4338ca;
}

.category-tag.no-category {
  background: #f1f5f9;
  color: #94a3b8;
  font-style: italic;
}

/* ================================================================
   TYPE BADGE
   ================================================================ */
.type-badge {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: 500;
}

.type-badge.stock-in {
  background: #dcfce7;
  color: #166534;
}

.type-badge.stock-out {
  background: #fee2e2;
  color: #991b1b;
}

/* ================================================================
   QUANTITY
   ================================================================ */
.quantity-value {
  font-weight: 700;
  font-size: 14px;
}

.quantity-value.positive {
  color: #166534;
}

.quantity-value.negative {
  color: #991b1b;
}

/* ================================================================
   PAGINATION
   ================================================================ */
.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 12px;
  margin-top: 16px;
  padding-top: 12px;
  border-top: 1px solid #e2e8f0;
  flex-wrap: wrap;
}

.page-btn {
  padding: 4px 12px;
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  cursor: pointer;
  font-size: 12px;
  transition: all 0.2s;
}

.page-btn:hover:not(:disabled) {
  background: #f1f5f9;
  border-color: #3b82f6;
}

.page-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.page-info {
  font-size: 12px;
  color: #64748b;
}

.limit-select {
  padding: 3px 8px;
  border: 1px solid #e2e8f0;
  border-radius: 4px;
  font-size: 12px;
  background: white;
  cursor: pointer;
}

/* ================================================================
   FOOTER
   ================================================================ */
.print-footer {
  text-align: center;
  margin-top: 20px;
  padding-top: 16px;
  border-top: 1px solid #e2e8f0;
  font-size: 11px;
  color: #94a3b8;
}

.print-footer p {
  margin: 4px 0;
}

/* ================================================================
   LOADING & ERROR LAYOUT
   ================================================================ */
.loading-state, .error-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 300px;
  font-family: sans-serif;
}

.spinner {
  border: 4px solid #f3f4f6;
  border-top: 4px solid #2563eb;
  border-radius: 50%;
  width: 35px;
  height: 35px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.error-icon {
  font-size: 48px;
  opacity: 0.5;
  margin-bottom: 12px;
}

.error-state h2 {
  color: #1e293b;
  margin-bottom: 8px;
}

.error-state p {
  color: #64748b;
  margin-bottom: 16px;
}

.btn-back {
  background: #f1f5f9;
  color: #1e293b;
  border: 1px solid #e2e8f0;
  padding: 8px 20px;
  border-radius: 8px;
  cursor: pointer;
  font-size: 13px;
}

/* ================================================================
   CRITICAL PRINT DRIVER OVERRIDES
   ================================================================ */
@media print {
  .no-print {
    display: none !important;
  }
  
  body {
    background-color: #fff;
    margin: 0 !important;
    padding: 0 !important;
  }
  
  .print-page {
    max-width: 100% !important;
    padding: 10px !important;
    margin: 0 !important;
    page-break-after: avoid;
  }
  
  .items-table {
    page-break-inside: auto;
  }
  
  .items-table tr {
    page-break-inside: avoid;
    page-break-after: auto;
  }
  
  .items-table thead {
    display: table-header-group;
  }
  
  .items-table th, 
  .items-table td {
    border-color: #000 !important;
  }
  
  .items-table th {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background-color: #d9d9d9 !important;
    color: #000000 !important;
  }
  
  .type-badge.stock-in {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background: #dcfce7 !important;
    color: #166534 !important;
  }
  
  .type-badge.stock-out {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background: #fee2e2 !important;
    color: #991b1b !important;
  }
  
  .category-tag {
    border: 1px solid #ddd;
    padding: 1px 6px;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  
  .category-tag.has-category {
    background: #e0e7ff !important;
    color: #4338ca !important;
  }
  
  .category-tag.no-category {
    background: #f1f5f9 !important;
    color: #94a3b8 !important;
  }
  
  .store-group-category-summary {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background: #f0f2f5 !important;
    border: 2px solid #d1d5db !important;
  }
  
  .summary-value {
    background: white !important;
    border: 1px solid #e2e8f0 !important;
  }
  
  .transaction-stats {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background: #f8fafc !important;
  }
  
  .stat-item.stock-in {
    border-left-color: #22c55e !important;
  }
  
  .stat-item.stock-out {
    border-left-color: #ef4444 !important;
  }
  
  .stat-item.total {
    border-left-color: #3b82f6 !important;
  }
  
  .filter-summary {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
    background: #f8fafc !important;
  }
  
  .form-header {
    page-break-after: avoid;
  }
  
  .item-common-name {
    font-weight: 600 !important;
    color: #000 !important;
  }
  
  .item-standard-name {
    color: #555 !important;
    font-style: italic !important;
  }
}

@media (max-width: 768px) {
  .store-group-category-summary {
    grid-template-columns: 1fr 1fr 1fr;
  }
  
  .transaction-stats {
    grid-template-columns: 1fr 1fr;
  }
  
  .items-table {
    font-size: 11px;
  }
  
  .items-table th, 
  .items-table td {
    padding: 4px 6px;
  }
  
  .filter-tags {
    flex-direction: column;
    gap: 4px;
  }
  
  .item-common-name {
    font-size: 12px;
  }
  
  .item-standard-name {
    font-size: 10px;
  }
}

@media (max-width: 480px) {
  .store-group-category-summary {
    grid-template-columns: 1fr 1fr;
  }
  
  .transaction-stats {
    grid-template-columns: 1fr;
  }
  
  .top-actions {
    flex-direction: column;
    gap: 8px;
  }
  
  .btn-back-top, .btn-print-top {
    width: 100%;
    text-align: center;
  }
}
</style>